# Generated by Django 5.2.9 on 2025-12-02 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentresult',
            options={},
        ),
        migrations.RenameField(
            model_name='tournamentresult',
            old_name='pontos_posicao',
            new_name='pontos_brutos',
        ),
        migrations.RemoveField(
            model_name='player',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='tournamentresult',
            name='observacoes',
        ),
        migrations.AlterField(
            model_name='player',
            name='apelido',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='core.season'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tournaments', to='core.tournamenttype'),
        ),
        migrations.AlterField(
            model_name='tournamententry',
            name='participou',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tournamententry',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.player'),
        ),
        migrations.AlterField(
            model_name='tournamententry',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.tournament'),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.player'),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='posicao',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.tournament'),
        ),
        migrations.CreateModel(
            name='SeasonInitialPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos_iniciais', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season_initial_points', to='core.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial_points', to='core.season')),
            ],
            options={
                'verbose_name': 'Pontos iniciais da temporada',
                'verbose_name_plural': 'Pontos iniciais da temporada',
                'unique_together': {('season', 'player')},
            },
        ),
    ]
