# Generated by Django 5.2.9 on 2025-12-02 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tournamentresult_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasoninitialpoints',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player'),
        ),
        migrations.AlterField(
            model_name='seasoninitialpoints',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.season'),
        ),
    ]
