# Generated by Django 5.2.9 on 2025-12-03 11:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_seasoninitialpoints_player_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournamentresult',
            old_name='pontos_brutos',
            new_name='pontos_base',
        ),
        migrations.AlterField(
            model_name='player',
            name='apelido',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='cpf',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='player',
            name='telefone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.season'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tournamenttype'),
        ),
        migrations.AlterField(
            model_name='tournamententry',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player'),
        ),
        migrations.AlterField(
            model_name='tournamententry',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tournament'),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player'),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='posicao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournamentresult',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tournament'),
        ),
        migrations.AlterField(
            model_name='tournamenttype',
            name='multiplicador_pontos',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='tournamenttype',
            name='usa_regras_padrao',
            field=models.BooleanField(default=True, help_text='Se marcado, usa a tabela padrão (1º=14, 2º=11, ..., 9º=2)'),
        ),
    ]
