# Generated by Django 5.2.9 on 2025-12-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamententry',
            name='confirmado_pelo_admin',
            field=models.BooleanField(default=False, help_text='Presença confirmada pelo organizador.'),
        ),
    ]
