# Generated by Django 5.2.9 on 2025-12-10 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_tournamententry_confirmado_pelo_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlindStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Regular 20min', max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Notas internas sobre o jogador', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('BLOQUEADO', 'Bloqueado'), ('VIP', 'VIP')], default='ATIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='active_tables',
            field=models.IntegerField(default=0, help_text='Número de mesas ativas no momento'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='current_level_order',
            field=models.IntegerField(default=1, help_text='Qual nível de blind está rodando agora?'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_paused',
            field=models.BooleanField(default=False, help_text='O relógio está pausado?'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='last_level_start',
            field=models.DateTimeField(blank=True, help_text='Hora que o nível começou ou despausou', null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_players_per_table',
            field=models.IntegerField(default=9, help_text='Max de jogadores por mesa (9-max, 6-max)'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rake',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Taxa administrativa', max_digits=10),
        ),
        migrations.AddField(
            model_name='tournament',
            name='seconds_remaining_at_pause',
            field=models.IntegerField(blank=True, help_text='Segundos restantes quando pausou', null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='stack_inicial',
            field=models.IntegerField(default=10000, help_text='Fichas iniciais'),
        ),
        migrations.AddField(
            model_name='tournamententry',
            name='ativo_no_jogo',
            field=models.BooleanField(default=True, help_text='False se o jogador já caiu'),
        ),
        migrations.AddField(
            model_name='tournamententry',
            name='buyin_pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournamententry',
            name='cadeira',
            field=models.IntegerField(blank=True, help_text='Número da cadeira', null=True),
        ),
        migrations.AddField(
            model_name='tournamententry',
            name='eliminado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamententry',
            name='mesa',
            field=models.IntegerField(blank=True, help_text='Número da mesa', null=True),
        ),
        migrations.AddField(
            model_name='tournamententry',
            name='posicao_eliminacao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournamententry',
            name='qtde_addons',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamententry',
            name='qtde_rebuys',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournamententry',
            name='valor_total_pago',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tournamentresult',
            name='premiacao_recebida',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tournamenttype',
            name='buyin_padrao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tournamenttype',
            name='rake_padrao',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor retido pela casa', max_digits=10),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('EM_ANDAMENTO', 'Em andamento'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='AGENDADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournamententry',
            name='confirmado_pelo_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tournamententry',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='core.tournament'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='blind_structure',
            field=models.ForeignKey(blank=True, help_text='Estrutura de blinds usada neste torneio', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.blindstructure'),
        ),
        migrations.CreateModel(
            name='BlindLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(help_text='1 para o primeiro nível, 2 para o segundo...')),
                ('small_blind', models.IntegerField(default=0)),
                ('big_blind', models.IntegerField(default=0)),
                ('ante', models.IntegerField(default=0, help_text='Ante único (Big Blind Ante) ou total da mesa')),
                ('tempo_minutos', models.PositiveIntegerField(default=20)),
                ('is_break', models.BooleanField(default=False, verbose_name='É intervalo?')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='core.blindstructure')),
            ],
            options={
                'ordering': ['ordem'],
                'unique_together': {('structure', 'ordem')},
            },
        ),
    ]
