# Generated by Django 5.2.9 on 2025-12-10 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_blindstructure_player_data_nascimento_player_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='addon_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo Add-on'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='percentage_rake',
            field=models.IntegerField(default=0, help_text='% extra retida do pote total (opcional)'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rebuy_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo Rebuy'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='time_chip_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo Time Chip (Staff)'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='active_tables',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='blind_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.blindstructure'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='buy_in',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor que vai para o pote', max_digits=10),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='current_level_order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='last_level_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='max_players_per_table',
            field=models.IntegerField(default=9),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='rake',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Taxa administrativa (Entry Fee)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='seconds_remaining_at_pause',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
