# Generated by Django 5.2.9 on 2025-12-11 20:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tournament_addon_cost_tournament_percentage_rake_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TournamentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterModelOptions(
            name='season',
            options={'verbose_name': 'Temporada', 'verbose_name_plural': 'Temporadas'},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['-data'], 'verbose_name': 'Torneio', 'verbose_name_plural': 'Torneios'},
        ),
        migrations.AlterModelOptions(
            name='tournamententry',
            options={'verbose_name': 'Inscrição', 'verbose_name_plural': 'Inscrições'},
        ),
        migrations.AlterModelOptions(
            name='tournamentresult',
            options={'verbose_name': 'Resultado', 'verbose_name_plural': 'Resultados'},
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='is_paused',
            new_name='permite_addon',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='active_tables',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='addon_cost',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='buy_in',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='current_level_order',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='garantido',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='last_level_start',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='max_players_per_table',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='percentage_rake',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='rake',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='rebuy_cost',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='seconds_remaining_at_pause',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='stack_inicial',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='time_chip_cost',
        ),
        migrations.RemoveField(
            model_name='tournamententry',
            name='ativo_no_jogo',
        ),
        migrations.RemoveField(
            model_name='tournamententry',
            name='buyin_pago',
        ),
        migrations.RemoveField(
            model_name='tournamententry',
            name='cadeira',
        ),
        migrations.RemoveField(
            model_name='tournamententry',
            name='eliminado_em',
        ),
        migrations.RemoveField(
            model_name='tournamententry',
            name='mesa',
        ),
        migrations.RemoveField(
            model_name='tournamententry',
            name='participou',
        ),
        migrations.RemoveField(
            model_name='tournamententry',
            name='posicao_eliminacao',
        ),
        migrations.RemoveField(
            model_name='tournamententry',
            name='qtde_addons',
        ),
        migrations.RemoveField(
            model_name='tournamententry',
            name='qtde_rebuys',
        ),
        migrations.RemoveField(
            model_name='tournamententry',
            name='usou_time_chip',
        ),
        migrations.RemoveField(
            model_name='tournamententry',
            name='valor_total_pago',
        ),
        migrations.AddField(
            model_name='season',
            name='pts_10lugar',
            field=models.IntegerField(default=1, help_text='Pontos para 10º lugar'),
        ),
        migrations.AddField(
            model_name='season',
            name='pts_1lugar',
            field=models.IntegerField(default=14, help_text='Pontos para 1º lugar'),
        ),
        migrations.AddField(
            model_name='season',
            name='pts_2lugar',
            field=models.IntegerField(default=11, help_text='Pontos para 2º lugar'),
        ),
        migrations.AddField(
            model_name='season',
            name='pts_3lugar',
            field=models.IntegerField(default=8, help_text='Pontos para 3º lugar'),
        ),
        migrations.AddField(
            model_name='season',
            name='pts_4lugar',
            field=models.IntegerField(default=6, help_text='Pontos para 4º lugar'),
        ),
        migrations.AddField(
            model_name='season',
            name='pts_5lugar',
            field=models.IntegerField(default=4, help_text='Pontos para 5º lugar'),
        ),
        migrations.AddField(
            model_name='season',
            name='pts_6lugar',
            field=models.IntegerField(default=2, help_text='Pontos para 6º lugar'),
        ),
        migrations.AddField(
            model_name='season',
            name='pts_7lugar',
            field=models.IntegerField(default=1, help_text='Pontos para 7º lugar'),
        ),
        migrations.AddField(
            model_name='season',
            name='pts_8lugar',
            field=models.IntegerField(default=1, help_text='Pontos para 8º lugar'),
        ),
        migrations.AddField(
            model_name='season',
            name='pts_9lugar',
            field=models.IntegerField(default=1, help_text='Pontos para 9º lugar'),
        ),
        migrations.AddField(
            model_name='season',
            name='tipo_calculo',
            field=models.CharField(choices=[('FIXO', 'Pontuação Fixa'), ('DINAMICO', 'Dinâmico (Field + Buy-in + Posição)')], default='FIXO', help_text='Sistema de cálculo de pontos para ranking', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='addon_rake_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='addon_rake_type',
            field=models.CharField(blank=True, choices=[('FIXO', 'Valor Fixo'), ('PERCENTUAL', 'Percentual'), ('MISTO', 'Fixo + Percentual')], default='FIXO', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='addon_rake_valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='addon_valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='buyin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='tournament',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_rebuys',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='permite_rebuy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='permite_rebuy_duplo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rake_percentual',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rake em % do pote', max_digits=5),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rake_type',
            field=models.CharField(choices=[('FIXO', 'Valor Fixo'), ('PERCENTUAL', 'Percentual'), ('MISTO', 'Fixo + Percentual')], default='FIXO', help_text='Tipo de cálculo de rake', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rake_valor',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rake fixo por buyin', max_digits=10),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rebuy_rake_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rebuy_rake_type',
            field=models.CharField(blank=True, choices=[('FIXO', 'Valor Fixo'), ('PERCENTUAL', 'Percentual'), ('MISTO', 'Fixo + Percentual')], default='FIXO', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rebuy_rake_valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rebuy_valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='timechip_valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Valor da venda de timechips (100% para house)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='total_jogadores',
            field=models.IntegerField(default=0, help_text='Total de jogadores que entraram'),
        ),
        migrations.AddField(
            model_name='tournamententry',
            name='data_inscricao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournament',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('EM_ANDAMENTO', 'Em Andamento'), ('ENCERRADO', 'Encerrado'), ('CANCELADO', 'Cancelado')], default='AGENDADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tournamenttype'),
        ),
        migrations.AlterField(
            model_name='tournamententry',
            name='pontos_participacao',
            field=models.IntegerField(default=0, help_text='Pontos por simplesmente participar'),
        ),
        migrations.AlterField(
            model_name='tournamententry',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tournament'),
        ),
        migrations.AddField(
            model_name='tournamentresult',
            name='premio_extra',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultado', to='core.tournamentprize'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='produtos',
            field=models.ManyToManyField(blank=True, related_name='tournaments', to='core.tournamentproduct'),
        ),
        migrations.CreateModel(
            name='PlayerProductPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=10)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tournament')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tournamentproduct')),
            ],
            options={
                'unique_together': {('tournament', 'player', 'product')},
            },
        ),
    ]
