# Generated by Django 5.2.9 on 2025-12-15 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_tournamentprize_tournamentproduct_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CAMPEAO', 'Campeão'), ('FINALISTA', 'Finalista'), ('CONSISTENTE', 'Consistente'), ('CRAQUE', 'Craque'), ('STREAKER', 'Streaker'), ('ALL_IN', 'All-in'), ('COMEBACK', 'Comeback'), ('HOT_STREAK', 'Hot Streak')], max_length=20)),
                ('descricao', models.CharField(max_length=200)),
                ('obtido_em', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.season')),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'unique_together': {('season', 'player', 'tipo')},
            },
        ),
        migrations.CreateModel(
            name='PlayerStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_torneios', models.IntegerField(default=0)),
                ('torneios_com_resultado', models.IntegerField(default=0)),
                ('vitórias', models.IntegerField(default=0)),
                ('top_3', models.IntegerField(default=0)),
                ('top_5', models.IntegerField(default=0)),
                ('total_buyin', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_premio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('roi', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('taxa_itm', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pontos_totais', models.IntegerField(default=0)),
                ('media_pontos', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.season')),
            ],
            options={
                'verbose_name': 'Estatística do Jogador',
                'verbose_name_plural': 'Estatísticas do Jogador',
                'unique_together': {('season', 'player')},
            },
        ),
    ]
