# Generated by Django 5.2.9 on 2025-12-16 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_tenant_tenantuser'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='playerstatistics',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='seasoninitialpoints',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='tournamententry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='player',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='playerachievement',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='playerstatistics',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='season',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='seasoninitialpoints',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='tournamententry',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AddField(
            model_name='tournamentresult',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='playerstatistics',
            unique_together={('season', 'player', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='seasoninitialpoints',
            unique_together={('season', 'player', 'tenant')},
        ),
        migrations.AlterUniqueTogether(
            name='tournamententry',
            unique_together={('tournament', 'player', 'tenant')},
        ),
    ]
