# Generated by Django 5.2.9 on 2025-12-16 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_playerstatistics_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamenttype',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant'),
        ),
    ]
