# Generated by Django 5.2.9 on 2025-12-16 21:37

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_blindlevel_tenant_blindstructure_tenant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamenttype',
            name='multiplicador_pontos',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Multiplicador de pontos (apenas usado no modo de pontuação FIXO)', max_digits=5),
        ),
        migrations.CreateModel(
            name='FinancialReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faturamento_esperado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rake_esperado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('premio_pool_esperado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('faturamento_real', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('premios_pagos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('diferenca', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('OK', 'Reconciliado ✓'), ('DISCREPANCY', 'Discrepância ⚠️'), ('ERROR', 'Erro Crítico ❌')], default='OK', max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('reconciliado_em', models.DateTimeField(auto_now=True)),
                ('reconciliado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation', to='core.tournament')),
            ],
            options={
                'verbose_name': 'Reconciliação Financeira',
                'verbose_name_plural': 'Reconciliações Financeiras',
                'ordering': ['-reconciliado_em'],
            },
        ),
        migrations.CreateModel(
            name='FinancialLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRY', 'Entrada de Buy-in'), ('REBUY', 'Rebuy'), ('ADDON', 'Add-on'), ('PRIZE', 'Premiação'), ('RAKE', 'Rake/Taxa'), ('REFUND', 'Devolução'), ('ADJUSTMENT', 'Ajuste')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descricao', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('alterado_em', models.DateTimeField(blank=True, null=True)),
                ('alterado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_logs_edited', to=settings.AUTH_USER_MODEL)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_logs_created', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.player')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_logs', to='core.tournament')),
            ],
            options={
                'verbose_name': 'Log Financeiro',
                'verbose_name_plural': 'Logs Financeiros',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['tournament', 'criado_em'], name='core_financ_tournam_946168_idx'), models.Index(fields=['player', 'criado_em'], name='core_financ_player__f1e468_idx')],
            },
        ),
    ]
