# Generated by Django 5.2.9 on 2025-12-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_tournamenttype_multiplicador_pontos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentproduct',
            name='entra_em_premiacao',
            field=models.BooleanField(default=False, help_text='Marque se este produto entra para o cálculo de premiação (ex: Add-on, Rebuy entram; Jack Pot, Staff não entram)'),
        ),
    ]
