# Generated by Django 5.2.9 on 2025-12-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_tournamentproduct_entra_em_premiacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='address_cep',
            field=models.CharField(blank=True, help_text='Formato: XXXXX-XXX', max_length=9),
        ),
        migrations.AddField(
            model_name='tenant',
            name='address_city',
            field=models.CharField(blank=True, help_text='Cidade', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='address_complement',
            field=models.CharField(blank=True, help_text='Apto, sala, etc', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='address_neighborhood',
            field=models.CharField(blank=True, help_text='Bairro', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='address_number',
            field=models.CharField(blank=True, help_text='Número do imóvel', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='address_state',
            field=models.CharField(blank=True, help_text='UF (SP, RJ, MG, etc)', max_length=2),
        ),
        migrations.AddField(
            model_name='tenant',
            name='address_street',
            field=models.CharField(blank=True, help_text='Nome da rua/avenida', max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='admin_cpf',
            field=models.CharField(blank=True, help_text='Formato: XXX.XXX.XXX-XX (opcional)', max_length=14),
        ),
        migrations.AddField(
            model_name='tenant',
            name='admin_full_name',
            field=models.CharField(blank=True, help_text='Nome completo do contato', max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='admin_phone',
            field=models.CharField(blank=True, help_text='Telefone do administrador', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='admin_role',
            field=models.CharField(blank=True, help_text='Cargo/Função (Proprietário, Gerente, etc)', max_length=50),
        ),
        migrations.AddField(
            model_name='tenant',
            name='club_cnpj',
            field=models.CharField(blank=True, help_text='Formato: XX.XXX.XXX/XXXX-XX', max_length=18, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='club_email',
            field=models.EmailField(blank=True, help_text='Email de contato do clube', max_length=254),
        ),
        migrations.AddField(
            model_name='tenant',
            name='club_phone',
            field=models.CharField(blank=True, help_text='Telefone principal', max_length=20),
        ),
        migrations.AddField(
            model_name='tenant',
            name='club_website',
            field=models.URLField(blank=True, help_text='Website do clube'),
        ),
    ]
