# Generated by Django 5.2.9 on 2025-12-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_tenant_address_cep_tenant_address_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='timechip_valor',
        ),
        migrations.AddField(
            model_name='tournament',
            name='staff_obrigatorio',
            field=models.BooleanField(default=False, help_text='Se marcado, STAFF é obrigatório no primeiro buy-in'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='staff_valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Taxa de STAFF cobrada no primeiro buy-in', max_digits=10, null=True),
        ),
    ]
