# Generated by Django 5.2.9 on 2025-12-18 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_timechip_to_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentPlayerPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('REBUY', 'Rebuy'), ('ADDON', 'Add-on')], max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade', models.IntegerField(default=1)),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tournament')),
            ],
            options={
                'verbose_name': 'Compra de Jogador (Rebuy/Add-on)',
                'verbose_name_plural': 'Compras de Jogador (Rebuy/Add-on)',
            },
        ),
    ]
