# Generated by Django 5.2.9 on 2025-12-18 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_tournament_player_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='addon_valor',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='max_rebuys',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='permite_addon',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='permite_rebuy',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='permite_rebuy_duplo',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='rebuy_valor',
        ),
    ]
