# Generated by Django 5.2.9 on 2025-12-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_tournament_addon_valor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentproduct',
            name='quantidade_maxima',
            field=models.IntegerField(blank=True, default=0, help_text='Máximo de vezes que este produto pode ser comprado (0 = ilimitado)'),
        ),
    ]
