# Generated by Django 5.2.9 on 2025-12-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_tournamentproduct_quantidade_maxima'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournamentplayerpurchase',
            options={'verbose_name': 'Compra de Jogador', 'verbose_name_plural': 'Compras de Jogador'},
        ),
        migrations.AlterField(
            model_name='tournamentplayerpurchase',
            name='tipo',
            field=models.CharField(choices=[('REBUY', 'Rebuy'), ('REBUY_DUPLO', 'Rebuy Duplo'), ('ADDON', 'Add-on')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='tournamentplayerpurchase',
            unique_together={('tournament', 'player', 'tipo')},
        ),
    ]
