# Generated by Django 5.2.9 on 2025-12-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_tournamentplayerpurchase_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='addon_valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Valor do add-on', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='permite_addon',
            field=models.BooleanField(default=False, help_text='Permite add-on (máx 1x por jogador)'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='permite_rebuy',
            field=models.BooleanField(default=False, help_text='Permite rebuy simples'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='permite_rebuy_duplo',
            field=models.BooleanField(default=False, help_text='Permite rebuy duplo (2x ou valor diferenciado)'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rebuy_duplo_valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Valor do rebuy duplo (se diferente, 2x rebuy simples)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rebuy_valor',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Valor do rebuy simples', max_digits=10, null=True),
        ),
    ]
