# Generated by Django 5.2.9 on 2025-12-18 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_tournament_addon_valor_tournament_permite_addon_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrizeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo', models.CharField(choices=[('PERCENTUAL', 'Percentual do Pote'), ('FIXO', 'Valores Fixos (R$)')], default='PERCENTUAL', max_length=20)),
                ('total_prize_pool', models.DecimalField(decimal_places=2, help_text='Valor total disponível para distribuição', max_digits=12)),
                ('itm_count', models.IntegerField(help_text='Quantidade de posições premiadas (In The Money)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('finalizado', models.BooleanField(default=False, help_text='Se True, não pode ser editado')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prize_structures_created', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
                ('tournament', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prize_structure', to='core.tournament')),
            ],
            options={
                'verbose_name': 'Estrutura de Prêmios',
                'verbose_name_plural': 'Estruturas de Prêmios',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PrizePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(help_text='1º, 2º, 3º lugar, etc')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Valor em reais a ser pago', max_digits=12)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentual do pote total (ex: 50.00 para 50%)', max_digits=5, null=True)),
                ('pago', models.BooleanField(default=False, help_text='Se o prêmio foi pago')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True)),
                ('metodo_pagamento', models.CharField(blank=True, help_text='Dinheiro, Pix, Transferência, etc', max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prize_payments_created', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prize_payments', to='core.player')),
                ('prize_structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.prizestructure')),
            ],
            options={
                'verbose_name': 'Prêmio por Posição',
                'verbose_name_plural': 'Prêmios por Posição',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='PrizeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Ex: 'Top 3 Clássico', 'Top 4 Balanceado'", max_length=255)),
                ('descricao', models.TextField(blank=True, help_text='Descrição e notas sobre quando usar')),
                ('modo', models.CharField(choices=[('PERCENTUAL', 'Percentual do Pote'), ('FIXO', 'Valores Fixos')], default='PERCENTUAL', max_length=20)),
                ('itm_count', models.IntegerField(help_text='Quantas posições são premiadas')),
                ('data', models.JSONField(help_text='Array com estrutura de prêmios: [{position: 1, percentage: 50, valor_fixo: null}, ...]')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prize_templates', to='core.tenant')),
            ],
            options={
                'verbose_name': 'Template de Prêmios',
                'verbose_name_plural': 'Templates de Prêmios',
                'ordering': ['itm_count', 'nome'],
            },
        ),
        migrations.AddIndex(
            model_name='prizestructure',
            index=models.Index(fields=['tournament', 'criado_em'], name='core_prizes_tournam_ed2e96_idx'),
        ),
        migrations.AddIndex(
            model_name='prizestructure',
            index=models.Index(fields=['tenant', 'criado_em'], name='core_prizes_tenant__98a4b9_idx'),
        ),
        migrations.AddIndex(
            model_name='prizepayment',
            index=models.Index(fields=['prize_structure', 'position'], name='core_prizep_prize_s_31133c_idx'),
        ),
        migrations.AddIndex(
            model_name='prizepayment',
            index=models.Index(fields=['player', 'pago'], name='core_prizep_player__7eeb0d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='prizepayment',
            unique_together={('prize_structure', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='prizetemplate',
            unique_together={('tenant', 'nome')},
        ),
    ]
