# Generated by Django 5.2.9 on 2025-12-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_prizestructure_prizepayment_prizetemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='current_level_order',
            field=models.IntegerField(default=1, help_text='Ordem do nível atual de blinds'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='is_paused',
            field=models.BooleanField(default=True, help_text='Se o timer está pausado'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='last_level_start',
            field=models.DateTimeField(blank=True, help_text='Quando o nível atual começou', null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='seconds_remaining_at_pause',
            field=models.IntegerField(blank=True, help_text='Segundos restantes quando pausado', null=True),
        ),
    ]
