# Generated by Django 5.2.9 on 2025-12-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_tournament_staff_chips_tournament_timechip_chips_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='timechip_valor',
        ),
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.ImageField(blank=True, help_text='Logo do clube para exibir nas telas (recomendado: 200x200px)', null=True, upload_to='tenant_logos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='timechip_chips',
            field=models.IntegerField(blank=True, default=0, help_text='Quantidade de fichas do Time Chip (confirmado pelo diretor)', null=True),
        ),
        migrations.AlterField(
            model_name='tournamentplayerpurchase',
            name='tipo',
            field=models.CharField(choices=[('REBUY', 'Rebuy'), ('REBUY_DUPLO', 'Rebuy Duplo'), ('ADDON', 'Add-on'), ('TIME_CHIP', 'Time Chip')], max_length=20),
        ),
    ]
