# Generated by Django 5.2.9 on 2025-12-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_tournament_timechip_valor_tenant_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto do jogador', null=True, upload_to='player_photos/%Y/%m/'),
        ),
    ]
