# Generated by Django 5.2.9 on 2025-12-30 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_player_foto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FINANCEIRO', 'Financeiro'), ('DESEMPENHO_JOGADOR', 'Desempenho do Jogador'), ('RANKING', 'Ranking'), ('TORNEIOS', 'Torneios'), ('ADMIN_GERAL', 'Administrativo Geral')], max_length=50)),
                ('periodo', models.CharField(choices=[('SEMANAL', 'Semanal'), ('MENSAL', 'Mensal'), ('TRIMESTRAL', 'Trimestral'), ('ANUAL', 'Anual'), ('CUSTOMIZADO', 'Customizado')], max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('dados', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('filtros', models.JSONField(default=dict)),
                ('gerado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tenant')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ReportDesempenho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_participacoes', models.IntegerField(default=0)),
                ('total_vitórias', models.IntegerField(default=0)),
                ('total_top3', models.IntegerField(default=0)),
                ('total_pontos', models.IntegerField(default=0)),
                ('total_investido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_ganho', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('roi', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('melhor_posicao', models.IntegerField(null=True)),
                ('pior_posicao', models.IntegerField(null=True)),
                ('posicao_media', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('evolucao_pontos', models.JSONField(default=list)),
                ('lucro_por_dia', models.JSONField(default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.player')),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='desempenho', to='core.report')),
                ('season', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.season')),
            ],
        ),
        migrations.CreateModel(
            name='ReportFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_buy_in', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_rebuy', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_addon', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_faturamento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_premiacao', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_rake', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lucro_liquido', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('numero_torneios', models.IntegerField(default=0)),
                ('numero_jogadores_unicos', models.IntegerField(default=0)),
                ('ticket_medio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('detalhes_por_tipo', models.JSONField(default=dict)),
                ('margem_bruta', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financeiro', to='core.report')),
            ],
        ),
        migrations.CreateModel(
            name='ReportRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_10', models.JSONField(default=list)),
                ('total_jogadores', models.IntegerField(default=0)),
                ('total_pontos_distribuidos', models.IntegerField(default=0)),
                ('pontos_medio_por_jogador', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('maiores_subidas', models.JSONField(default=list)),
                ('maiores_quedas', models.JSONField(default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to='core.report')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.season')),
            ],
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['tenant', 'tipo', '-criado_em'], name='core_report_tenant__d89150_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['tenant', 'data_inicio', 'data_fim'], name='core_report_tenant__b831fe_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reportdesempenho',
            unique_together={('report', 'player', 'season')},
        ),
    ]
