# Generated by Django 5.2.9 on 2025-12-31 01:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_report_reportdesempenho_reportfinanceiro_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='playerproductpurchase',
            name='data_lancamento',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Momento exato do registro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerproductpurchase',
            name='lancado_por',
            field=models.ForeignKey(blank=True, help_text='Usuário que registrou esta compra', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rebuy_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='playerproductpurchase',
            index=models.Index(fields=['tournament', 'player'], name='core_player_tournam_422e80_idx'),
        ),
        migrations.AddIndex(
            model_name='playerproductpurchase',
            index=models.Index(fields=['-data_lancamento'], name='core_player_data_la_3ad7c2_idx'),
        ),
    ]
