# Generated by Django 5.2.9 on 2026-01-13 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_playerproductpurchase_data_lancamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerproductpurchase',
            name='observacao',
            field=models.TextField(blank=True, help_text='Nota ou observação do admin sobre este rebuy/addon', null=True),
        ),
    ]
