# Generated by Django 5.2.9 on 2026-01-26 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_add_email_password_tokens'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGIN_FAILED', 'Login Falhou'), ('LOGOUT', 'Logout'), ('CREATE', 'Criar'), ('UPDATE', 'Atualizar'), ('DELETE', 'Deletar'), ('VIEW', 'Visualizar'), ('EXPORT', 'Exportar'), ('PERMISSION_CHANGE', 'Mudança de Permissão'), ('TENANT_CHANGE', 'Mudança de Tenant'), ('SECURITY_ALERT', 'Alerta de Segurança')], max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('object_description', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='core.tenant')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoria de Tenant',
                'verbose_name_plural': 'Auditorias de Tenant',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='core_tenant_tenant__fd8bcd_idx'), models.Index(fields=['user', '-created_at'], name='core_tenant_user_id_ea1072_idx'), models.Index(fields=['action', '-created_at'], name='core_tenant_action_0599c1_idx'), models.Index(fields=['ip_address', '-created_at'], name='core_tenant_ip_addr_9c7c44_idx')],
            },
        ),
    ]
