# Generated by Django 5.2.9 on 2026-01-28 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_add_tenant_audit_log'),
    ]

    operations = [
        # Phase 6: Advanced Features
        migrations.AddField(
            model_name='tournament',
            name='parent_tournament',
            field=models.ForeignKey(blank=True, help_text='Torneio original se este é uma duplicação', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tournament'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='serie_recorrencia',
            field=models.CharField(blank=True, choices=[('semanal', 'Semanal'), ('mensal', 'Mensal'), ('bimestral', 'Bimestral')], help_text='Define recorrência da série', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='serie_proxima_data',
            field=models.DateTimeField(blank=True, help_text='Data do próximo torneio em uma série', null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='ultima_acao_tipo',
            field=models.CharField(blank=True, help_text='Tipo da última ação realizada (para undo)', max_length=50),
        ),
        migrations.AddField(
            model_name='tournament',
            name='ultima_acao_dados',
            field=models.JSONField(blank=True, help_text='Dados da última ação para possível undo', null=True),
        ),
        # Update STATUS_CHOICES to include RASCUNHO
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('EM_ANDAMENTO', 'Em Andamento'), ('ENCERRADO', 'Encerrado'), ('CANCELADO', 'Cancelado'), ('RASCUNHO', 'Rascunho')], default='AGENDADO', max_length=20),
        ),
    ]
